// app/layout.js
import "./globals.css";

export const metadata = {
  title: "CyberPulse AI — Automated Threat Intelligence",
  description:
    "Real-time cybersecurity news, CVE disclosures, and incident analysis — generated by AI from trusted sources.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
